### ISSUE TITLE
Unificar endpoints

### ISSUE THREAD

**Issue by brfreitas** [codenation-dev/squad-6-java-2#2]
https://github.com/codenation-dev/squad-6-java-2/blob/51a223609f51ef1edb62e197ed11e6a94872c8b1/central-erros/src/main/java/br/com/codenation/endpoints/LogController.java#L52

no controller do Log existem três métodos/endpoints, são eles:
* filterByDescription
* filterByLevel
* filterBySource 

Afim de ter uma api mais limpa sugiro a unificação destes três endpoints em um único que possa receber os três tipos de filtro.

**Comment by bmaximo** [comment]
Endpoint corrigido no master central-erros/src/main/java/br/com/codenation/endpoints/LogController.java
